name: 'Simple Issue Labeler'
description: 'Adds labels to new issues.'
inputs:
  repo-token:
    description: 'Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true
  labels:
    description: 'Labels to add to an issue, seperated by commas.'
    required: true
branding:
  icon: zap-off
  color: orange
runs:
  using: 'node12'
  main: 'label.js'
